export type Product = {
  slug: string;
  name: string;
  category: string;
  categorySlug: string;
  primaryKeyword: string;
  secondaryKeywords: string[];
  intent: "transactional" | "commercial";
  metaTitle: string;
  metaDescription: string;
  summary: string;
  images: string[];
  tags: string[];
  features: string[];
  customization: string[];
  applications: string[];
  complianceNote?: string;
  specs?: ProductSpecs;
};

/** Verified factory data for a specific model, used on the product detail page. */
export type ProductSpecs = {
  model: string;
  colors?: string;
  battery?: string;
  power?: string;
  productSize?: string;
  netGrossWeight?: string;
  packageSize?: string;
  cartonSize?: string;
  cartonWeight?: string;
};

/**
 * Commercial terms that apply across the massager range. Kept in one place so a
 * change to MOQ, lead time or warranty never has to be edited product by product.
 */
export const tradeTerms = {
  moqBranding: "1,000 pcs per item for custom logo, manual or packaging",
  moqColor: "2,000 pcs per item for a custom colour",
  included: "Certified adapter, car plug, user manual and colour box in every set",
  motor: "Pure copper motor for longer service life, lower noise and higher torque",
  materials: "Eco-friendly ABS for massage heads and inner modules",
  certifications: ["FDA", "UL", "CE", "RoHS", "UKCA", "KC", "ISO 9001"],
  warranty: "12-month quality warranty",
  leadTime: "20-30 working days for orders below 5,000 pcs; negotiated above that volume",
  paymentBulk: "Bulk orders: 30% T/T on PI confirmation, 70% balance before shipment",
  paymentSmall: "Small orders: 100% T/T on PI confirmation",
  quoteValidity: "Quotations valid for one month",
};

export type Category = {
  slug: string;
  name: string;
  primaryKeyword: string;
  secondaryKeywords: string[];
  metaTitle: string;
  metaDescription: string;
  heading: string;
  intro: string;
  buyerNote: string;
  image: string;
};

export const categories: Category[] = [
  {
    slug: "massage-guns",
    name: "Massage Guns",
    primaryKeyword: "massage gun manufacturer",
    secondaryKeywords: ["percussion massage gun supplier", "fascia gun OEM factory", "private label massage gun"],
    metaTitle: "Massage Gun Manufacturer | OEM & Private Label Factory",
    metaDescription:
      "China massage gun manufacturer supplying percussion, heated and cooling fascia gun platforms for OEM, private-label and wholesale programs in Europe and North America.",
    heading: "Massage gun and fascia gun manufacturing",
    intro:
      "Percussion massage platforms covering full-size, compact and thermal-attachment formats. Each model is quoted with its own motor, stroke, battery and attachment configuration.",
    buyerNote: "Four percussion platforms, including hot-and-cold and cooling-design concepts.",
    image: "/products/11/image-1.jpg",
  },
  {
    slug: "neck-shoulder-massagers",
    name: "Neck & Shoulder Massagers",
    primaryKeyword: "neck and shoulder massager manufacturer",
    secondaryKeywords: ["shiatsu neck massager supplier", "wearable neck massager factory", "OEM neck massager China"],
    metaTitle: "Neck & Shoulder Massager Manufacturer | OEM Supplier",
    metaDescription:
      "Neck and shoulder massager manufacturer producing wearable, wrap, U-shaped and kneading formats for private-label and wholesale buyers in Europe and North America.",
    heading: "Neck and shoulder massager manufacturing",
    intro:
      "Wearable and wrap-style neck platforms for retail, gifting and e-commerce ranges. Available with kneading mechanisms, optional heat and a choice of power configurations.",
    buyerNote: "Six neck and shoulder platforms across wearable, wrap and structured formats.",
    image: "/products/3/image-1.jpg",
  },
  {
    slug: "foot-massagers",
    name: "Foot Massagers",
    primaryKeyword: "foot massager manufacturer",
    secondaryKeywords: ["shiatsu foot massager supplier", "foot and calf massager factory", "OEM foot massage machine"],
    metaTitle: "Foot Massager Manufacturer | Shiatsu & OEM Supplier",
    metaDescription:
      "Foot massager manufacturer supplying enclosed shiatsu foot and calf massage machines for branded home-wellness, retail and distribution programs.",
    heading: "Foot massager manufacturing",
    intro:
      "Enclosed dual-foot and foot-plus-calf platforms for premium home-wellness ranges. Roller layout, heat function and voltage configuration are model specific.",
    buyerNote: "Two enclosed foot platforms covering feet only and feet with lower calves.",
    image: "/products/9/image-1.png",
  },
  {
    slug: "leg-massagers",
    name: "Leg Massagers",
    primaryKeyword: "leg massager manufacturer",
    secondaryKeywords: ["air compression leg massager supplier", "compression boots manufacturer", "OEM leg massager factory"],
    metaTitle: "Leg Massager Manufacturer | Air Compression OEM Supplier",
    metaDescription:
      "Air compression leg massager manufacturer producing calf sleeves and full-leg recovery boots for sports recovery, wellness retail and private-label programs.",
    heading: "Compression leg massager manufacturing",
    intro:
      "Pneumatic compression platforms from calf sleeves to full lower-leg boots. Specified by chamber count, pressure range and controller type to suit your programme.",
    buyerNote: "Two compression platforms for calf-only and full lower-leg recovery.",
    image: "/products/8/image-1.jpg",
  },
  {
    slug: "massage-pillows-cushions",
    name: "Massage Pillows & Cushions",
    primaryKeyword: "massage pillow manufacturer",
    secondaryKeywords: ["shiatsu massage pillow supplier", "massage seat cushion manufacturer", "back massage cushion OEM"],
    metaTitle: "Massage Pillow & Seat Cushion Manufacturer | OEM Supplier",
    metaDescription:
      "Massage pillow and seat cushion manufacturer supplying compact kneading pillows and full-back chair cushions for retail, automotive and office wellness programs.",
    heading: "Massage pillow and seat cushion manufacturing",
    intro:
      "Compact kneading pillows and chair-mounted full-back cushions. Node layout, heat option and control method are defined by the selected model.",
    buyerNote: "Three platforms covering compact pillows and full-back seat cushions.",
    image: "/products/16/image-1.jpg",
  },
  {
    slug: "targeted-body-massagers",
    name: "Targeted Body Massagers",
    primaryKeyword: "targeted body massager manufacturer",
    secondaryKeywords: ["hand massager supplier", "lumbar massage belt manufacturer", "facial massager OEM factory"],
    metaTitle: "Hand, Waist & Facial Massager Manufacturer | OEM Supplier",
    metaDescription:
      "Targeted massager manufacturer producing hand, lumbar, ankle and facial care devices for private-label wellness, beauty and personal-care ranges.",
    heading: "Targeted body massager manufacturing",
    intro:
      "Focused-area devices for hands, lower back, ankles and facial care. Available with heat, EMS and vibration configurations to suit your range.",
    buyerNote: "Five targeted platforms across hand, lumbar, ankle and facial formats.",
    image: "/products/21/image-1.jpg",
  },
];

export const getCategory = (slug: string) => categories.find((category) => category.slug === slug);
export const productsByCategory = (slug: string) => products.filter((product) => product.categorySlug === slug);

const gallery = (folder: number, count: number, pngPositions: number[] = []) =>
  Array.from({ length: count }, (_, index) => `/products/${folder}/image-${index + 1}.${pngPositions.includes(index + 1) ? "png" : "jpg"}`);

export const products: Product[] = [
  {
    slug: "wearable-neck-massager",
    name: "Wearable Neck Massager",
    category: "Neck & Shoulder Massagers",
    categorySlug: "neck-shoulder-massagers",
    primaryKeyword: "wearable neck massager manufacturer",
    secondaryKeywords: ["cordless neck massager supplier", "private label neck massager", "OEM wearable massager China"],
    intent: "transactional",
    metaTitle: "Wearable Neck Massager Manufacturer | OEM & Private Label",
    metaDescription:
      "Wearable neck massager manufacturer in China. Open-neck cordless format for private-label wellness brands, retail chains and e-commerce programs. Request MOQ and OEM options.",
    summary: "An open-neck wearable format for private-label wellness and personal-care programs.",
    images: gallery(1, 4),
    tags: ["OEM / ODM", "Private label", "Sample inquiry"],
    specs: {
      model: "NM22 / ST-304",
      colors: "White",
      battery: "1200 mAh; 120 min charge, 300 min runtime",
      power: "5W / DC 5V 1A",
      productSize: "16 x 16 x 5 cm",
      netGrossWeight: "300 g / 325 g",
      packageSize: "18 x 16 x 6 cm",
      cartonSize: "51.5 x 35 x 24.5 cm (24 pcs/carton)",
      cartonWeight: "9 kg",
    },
    features: [
      "Six modes with 15 freely adjustable intensity levels",
      "TENS pulse output modelled on traditional massage techniques",
      "Constant-temperature heat with intelligent temperature control",
      "Voice prompts and smart remote control",
      "Customisable voice-broadcast version available for your brand",
      "1200 mAh battery: 120-minute charge for 300 minutes of use",
    ],
    customization: ["Logo", "Color", "Packaging", "Market configuration"],
    applications: ["Wellness retail", "E-commerce brands", "Corporate gifting"],
  },
  {
    slug: "shiatsu-neck-shoulder-massager",
    name: "Shiatsu Neck and Shoulder Massager",
    category: "Neck & Shoulder Massagers",
    categorySlug: "neck-shoulder-massagers",
    primaryKeyword: "shiatsu neck and shoulder massager manufacturer",
    secondaryKeywords: ["shiatsu massager supplier China", "car and home neck massager OEM", "wholesale shiatsu massager"],
    intent: "transactional",
    metaTitle: "Shiatsu Neck & Shoulder Massager Manufacturer | OEM Supplier",
    metaDescription:
      "Shiatsu neck and shoulder massager manufacturer supplying wrap-style platforms with home and vehicle power options for wholesale and private-label buyers.",
    summary: "A plug-in wrap-style massage platform supplied with home and vehicle power options.",
    images: gallery(2, 5, [1, 3, 4, 5]),
    tags: ["Home and car use", "OEM / ODM", "B2B supply"],
    specs: {
      model: "OY-S003",
      colors: "Black / Red",
      power: "Input 110-240V; Output DC 12.6V 1A; Rated power 24W",
      productSize: "50 x 40 cm",
      netGrossWeight: "1.3 / 1.5 kg",
      packageSize: "40 x 21 x 17 cm",
      cartonSize: "53.5 x 41.5 x 42 cm (6 pcs/carton)",
      cartonWeight: "9.3 / 12.6 kg",
    },
    features: [
      "Shiatsu kneading heads that reverse in two directions",
      "Infrared heating with two selectable intensities",
      "Three speeds adjustable from weak to strong",
      "Controller lights indicate remaining battery charge",
      "15-minute auto-off timer",
      "Covers neck, shoulder, back, waist, abdomen, arm, leg and foot",
      "Lithium battery plus mains adapter and car plug for home, office or vehicle use",
      "Gift-box packed for retail and corporate gifting",
    ],
    customization: ["Upholstery", "Control layout", "Logo", "Retail box"],
    applications: ["Home wellness retail", "Automotive accessory channels", "Distributor programs"],
  },
  {
    slug: "kneading-neck-shoulder-massager",
    name: "Kneading Neck and Shoulder Massager",
    category: "Neck & Shoulder Massagers",
    categorySlug: "neck-shoulder-massagers",
    primaryKeyword: "kneading neck and shoulder massager supplier",
    secondaryKeywords: ["shoulder massager wholesale China", "pull strap massager manufacturer", "private label shoulder wrap"],
    intent: "transactional",
    metaTitle: "Kneading Neck & Shoulder Massager Supplier | Wholesale OEM",
    metaDescription:
      "Kneading neck and shoulder massager supplier producing pull-strap shoulder wraps for wholesale, private-label and distributor massage ranges.",
    summary: "A pull-strap shoulder wrap designed for wholesale and private-label massage ranges.",
    images: gallery(3, 6),
    tags: ["Pull-strap design", "Private label", "Wholesale"],
    specs: {
      model: "WY-NM19",
      colors: "Black / Blue",
      power: "Input 110-240V; Output DC 12.6V 1A; Rated power 24W",
      productSize: "50 x 40 cm",
      netGrossWeight: "1.3 / 1.5 kg",
      packageSize: "40 x 17 x 20 cm",
      cartonSize: "53.5 x 41.5 x 42 cm (6 pcs/carton)",
      cartonWeight: "9.3 / 12.6 kg",
    },
    features: [
      "Kneading massage combined with infrared heating",
      "Soft shiatsu heads that reverse in two directions",
      "Three speeds adjustable from weak to strong",
      "15-minute auto-off timer",
      "Covers neck, shoulder, back, waist, abdomen, arm, leg and foot",
      "Mains adapter and car plug supplied for home, office or vehicle use",
      "Gift-box packed for retail and corporate gifting",
    ],
    customization: ["Fabric", "Color", "Controls", "Packaging"],
    applications: ["Wholesale distribution", "Pharmacy and wellness retail", "Promotional programs"],
  },
  {
    slug: "heated-neck-shoulder-massager",
    name: "Heated Neck and Shoulder Massager",
    category: "Neck & Shoulder Massagers",
    categorySlug: "neck-shoulder-massagers",
    primaryKeyword: "heated neck and shoulder massager manufacturer",
    secondaryKeywords: ["heat therapy neck massager supplier", "U shape shoulder massager OEM", "heated massager factory China"],
    intent: "transactional",
    metaTitle: "Heated Neck & Shoulder Massager Manufacturer | OEM Factory",
    metaDescription:
      "Heated neck and shoulder massager manufacturer supplying U-shaped platforms with integrated controls and heat options for branded retail programs.",
    summary: "A U-shaped shoulder massage platform with an integrated control area for branded programs.",
    images: gallery(4, 6),
    tags: ["Heat option", "OEM / ODM", "Retail-ready format"],
    specs: {
      model: "OY18NM17",
      colors: "Black / Grey",
      power: "Input 110-240V; Output DC 12V 2A; Rated power 24W",
      productSize: "50 x 40 cm",
      netGrossWeight: "1.3 / 1.5 kg",
      packageSize: "40 x 17 x 20 cm",
      cartonSize: "53.5 x 41.5 x 42 cm (6 pcs/carton)",
      cartonWeight: "9.3 / 12.6 kg",
    },
    features: [
      "Infrared heating reaching approximately 45 C",
      "Shiatsu kneading heads that reverse in two directions",
      "Branded pure copper motor for durability, quiet running and torque",
      "Three speeds adjustable from weak to strong",
      "15-minute auto-off timer",
      "Eco-friendly ABS massage heads and inner module",
      "PU leather finish with a matching carry bag",
      "Mains adapter and car plug supplied for home, office or vehicle use",
    ],
    customization: ["Logo", "Materials", "Heat settings", "Gift box"],
    applications: ["Retail chains", "Seasonal gifting", "Wellness e-commerce"],
  },
  {
    slug: "wraparound-shoulder-massager",
    name: "Wraparound Shoulder Massager",
    category: "Neck & Shoulder Massagers",
    categorySlug: "neck-shoulder-massagers",
    primaryKeyword: "wraparound shoulder massager supplier",
    secondaryKeywords: ["padded shoulder massager manufacturer", "upper body massager wholesale", "OEM massage wrap China"],
    intent: "transactional",
    metaTitle: "Wraparound Shoulder Massager Supplier | B2B OEM Factory",
    metaDescription:
      "Wraparound shoulder massager supplier producing padded upper-body massage wraps for distributor, retail and private-label product collections.",
    summary: "A padded wraparound massage format for shoulder and upper-body product collections.",
    images: gallery(5, 4),
    tags: ["Padded wrap", "OEM available", "B2B quotation"],
    specs: {
      model: "WY-NM15",
      colors: "Black",
      power: "Input 110-240V; Output DC 12.6V 1A; Rated power 24W",
      productSize: "50 x 40 cm",
      netGrossWeight: "1.3 / 1.5 kg",
      packageSize: "40 x 21 x 17 cm",
      cartonSize: "53.5 x 41.5 x 42 cm (6 pcs/carton)",
      cartonWeight: "9.3 / 12.6 kg",
    },
    features: [
      "Kneading massage combined with infrared heating",
      "Soft shiatsu heads that reverse in two directions",
      "Three speeds adjustable from weak to strong",
      "15-minute auto-off timer",
      "Mains adapter and car plug supplied for home, office or vehicle use",
      "Wrap-over arm straps for hands-free positioning",
    ],
    customization: ["Surface material", "Color", "Control panel", "Branding"],
    applications: ["Distributor ranges", "Home comfort retail", "Private-label collections"],
  },
  {
    slug: "u-shaped-neck-massager",
    name: "U-Shaped Neck Massager",
    category: "Neck & Shoulder Massagers",
    categorySlug: "neck-shoulder-massagers",
    primaryKeyword: "U shaped neck massager manufacturer",
    secondaryKeywords: ["travel neck massager supplier", "neck massage pillow OEM", "gift neck massager wholesale"],
    intent: "transactional",
    metaTitle: "U-Shaped Neck Massager Manufacturer | OEM & Gift Programs",
    metaDescription:
      "U-shaped neck massager manufacturer supplying structured neck massage platforms for consumer wellness, travel retail and gifting ranges.",
    summary: "A structured U-shaped neck massage platform for consumer wellness and gifting ranges.",
    images: gallery(18, 6),
    tags: ["U-shaped form", "Neck-focused", "OEM available"],
    specs: {
      model: "HT-ST321",
      colors: "Grey",
      battery: "1500 mAh",
      power: "Input DC 5V 2A; charging power 10W",
      productSize: "22 x 22.5 x 8.5 cm",
      netGrossWeight: "1100 g gross with colour box",
      packageSize: "24.5 x 25.5 x 9.5 cm",
      cartonSize: "52.5 x 51.5 x 31 cm (12 pcs/carton)",
      cartonWeight: "13 kg",
    },
    features: [
      "Earphone-style clamping design that mimics manual deep-pressure technique",
      "Independent heating switch with smart heat control",
      "Three modes: normal, fast and inching",
      "1500 mAh battery for cordless use",
      "Simple single-hand operation",
    ],
    customization: ["Surface material", "Color", "Logo", "Gift box"],
    applications: ["Travel retail", "Gift programs", "Wellness e-commerce"],
  },
  {
    slug: "hot-cold-massage-gun",
    name: "Hot and Cold Massage Gun",
    category: "Massage Guns",
    categorySlug: "massage-guns",
    primaryKeyword: "hot and cold massage gun manufacturer",
    secondaryKeywords: ["heated massage gun supplier", "thermal percussion gun OEM", "hot cold therapy gun factory"],
    intent: "transactional",
    metaTitle: "Hot & Cold Massage Gun Manufacturer | OEM Factory China",
    metaDescription:
      "Hot and cold massage gun manufacturer producing percussion platforms with thermal attachments for recovery brands, sports retail and private-label ranges.",
    summary: "A percussion massage gun with hot and cold therapy attachments for recovery ranges.",
    images: gallery(11, 6),
    tags: ["Hot and cold head", "Percussion format", "OEM / ODM"],
    features: ["Interchangeable heads", "Hot & Cold Therapy Attachment", "Adjustable hot and cold temperature settings"],
    customization: ["Color", "Attachments", "Logo", "Carrying case"],
    applications: ["Sports recovery brands", "Physiotherapy channels", "Premium retail"],
  },
  {
    slug: "deep-tissue-massage-gun",
    name: "Deep Tissue Massage Gun",
    category: "Massage Guns",
    categorySlug: "massage-guns",
    primaryKeyword: "deep tissue massage gun manufacturer",
    secondaryKeywords: ["professional massage gun supplier", "percussion massager wholesale China", "fascia gun OEM factory"],
    intent: "transactional",
    metaTitle: "Deep Tissue Massage Gun Manufacturer | Wholesale OEM Supplier",
    metaDescription:
      "Deep tissue massage gun manufacturer supplying full-size percussion platforms with multiple attachments for wholesale, OEM and private-label programs.",
    summary: "A full-size percussion massage gun with multiple attachment options for wholesale programs.",
    images: gallery(12, 6),
    tags: ["Multiple attachments", "OEM available", "Wholesale"],
    specs: {
      model: "HT-HN026",
      colors: "Grey, Black, Blue, Carbon",
      battery: "2500 mAh; 2-3 h charge for 4-6 h use",
      power: "Input 110-240V 50/60Hz; 24V brushless motor 20W; 1300-3200 RPM",
      productSize: "23.6 x 16.6 x 7.5 cm",
      packageSize: "28.5 x 23.8 x 10.2 cm",
      cartonSize: "52.5 x 36.5 x 51.5 cm (10 pcs/carton)",
    },
    features: [
      "Seven intensity levels across a 1300-3200 RPM range",
      "Eight massage heads for different muscle groups",
      "Brushless silent motor running below 50 dB",
      "Dedicated charging chip with constant current and voltage",
      "Overheat and overcharge protection",
      "LCD touch controls with remaining-power display",
      "2500 mAh battery: 2-3 h charge for 4-6 h of use",
      "Handheld bag and gift box packing",
    ],
    customization: ["Shell color", "Attachments", "Display", "Case and packaging"],
    applications: ["Fitness and gym channels", "Sports retail", "Distributor programs"],
  },
  {
    slug: "mini-massage-gun",
    name: "Mini Massage Gun",
    category: "Massage Guns",
    categorySlug: "massage-guns",
    primaryKeyword: "mini massage gun manufacturer",
    secondaryKeywords: ["portable massage gun supplier", "travel massage gun OEM", "compact fascia gun wholesale"],
    intent: "transactional",
    metaTitle: "Mini Massage Gun Manufacturer | Portable OEM Supplier",
    metaDescription:
      "Mini massage gun manufacturer producing compact percussion platforms for travel retail, gifting and high-volume e-commerce programs.",
    summary: "A compact percussion massage gun platform for travel, gifting and e-commerce ranges.",
    images: gallery(13, 6),
    tags: ["Compact format", "Private label", "Retail program"],
    specs: {
      model: "HT-HN049",
      colors: "Black, White, Red, Green",
      battery: "2000 mAh Li-ion, USB charging; 2-2.5 h full charge",
      power: "Rated output 5V 2A; rated power 30W",
      productSize: "15.5 x 17 x 5.5 cm",
      netGrossWeight: "0.42 kg",
      cartonSize: "52.5 x 26.5 x 44.3 cm (12 pcs/carton)",
    },
    features: [
      "Five interchangeable massage heads for different body areas",
      "Brushless motor running below 55 dB",
      "Five adjustable intensity levels",
      "Heating and cooling head: 45-50 C heat and 13-19 C cooling",
      "Runtime: 1.5-2 h normal, 3 h heated, 40 min cooling",
      "Auto-off: 15 min normal, 10 min heated, 6 min cooling",
      "Four colourways and luxury bag packing per unit",
    ],
    customization: ["Color", "Logo", "Attachment set", "Gift box"],
    applications: ["E-commerce marketplaces", "Travel retail", "Promotional gifting"],
  },
  {
    slug: "cooling-massage-gun",
    name: "Cooling Massage Gun",
    category: "Massage Guns",
    categorySlug: "massage-guns",
    primaryKeyword: "cooling massage gun supplier",
    secondaryKeywords: ["cold therapy massage gun manufacturer", "massage gun with cooling OEM", "recovery gun factory China"],
    intent: "transactional",
    metaTitle: "Cooling Massage Gun Supplier | Cold Therapy OEM Factory",
    metaDescription:
      "Cooling massage gun supplier producing percussion platforms with cold-therapy design for sports recovery, wellness retail and OEM brand programs.",
    summary: "A full-size percussion massage gun with a rear cooling plate for extended sessions.",
    images: gallery(14, 6),
    tags: ["Cooling Plate", "OEM / ODM", "Accessory set"],
    specs: {
      model: "HT-HN062",
      colors: "Black, Grey",
      battery: "2500 mAh for 4-5 h use",
      power: "Input DC 16.8V 1A; rated 16.8V 20W; brushless motor",
      productSize: "16.5 x 21 x 6 cm",
      packageSize: "29.5 x 23.5 x 8.5 cm",
      cartonSize: "44 x 30.5 x 47.5 cm (10 pcs/carton)",
    },
    features: [
      "30 speed modes for a wide range of recovery protocols",
      "16.8V brushless silent motor",
      "Eight massage heads for different body areas",
      "Large LCD screen showing speed and remaining power",
      "2500 mAh battery for 4-5 hours of use",
      "20-minute auto-off timer",
      "Non-slip handle with single-button power control",
      "Handheld bag packing",
    ],
    customization: ["Color", "Logo", "Head set", "Storage case"],
    applications: ["Sports recovery brands", "Performance retail", "Specialist distributors"],
  },
  {
    slug: "shiatsu-foot-massager-machine",
    name: "Shiatsu Foot Massager Machine",
    category: "Foot Massagers",
    categorySlug: "foot-massagers",
    primaryKeyword: "shiatsu foot massager manufacturer",
    secondaryKeywords: ["electric foot massager supplier", "foot massage machine OEM", "wholesale foot massager China"],
    intent: "transactional",
    metaTitle: "Shiatsu Foot Massager Manufacturer | OEM & Wholesale Factory",
    metaDescription:
      "Shiatsu foot massager manufacturer supplying enclosed dual-foot massage machines with heat options for branded home-wellness and retail ranges.",
    summary: "An enclosed dual-foot massage platform for branded home-wellness ranges.",
    images: gallery(9, 4, [1, 2, 3, 4]),
    tags: ["Enclosed foot system", "OEM / ODM", "Wholesale"],
    specs: {
      model: "WY-FN054",
      colors: "Black",
      power: "Input 100-240V 50/60Hz; Output 24V 1.5A; Power 36W",
      productSize: "410 x 350 x 210 mm",
      netGrossWeight: "3.83 kg",
      cartonSize: "46 x 39.8 x 46.5 cm (2 pcs/carton)",
    },
    features: [
      "Constant 41 C infrared heating",
      "Three adjustable air-compression levels",
      "Three massage programmes with rolling shiatsu action",
      "Kneading air pressure for the tops of the feet and ankles",
      "Three methods combined: rolling, scraping and air compression",
      "Selectable auto-off at 5, 10, 15, 20, 25 or 30 minutes",
      "Single On/Off button with intensity selection",
    ],
    customization: ["Housing color", "Control panel", "Power configuration", "Packaging"],
    applications: ["Home wellness retail", "Senior care channels", "Department store ranges"],
  },
  {
    slug: "foot-and-calf-massager",
    name: "Foot and Calf Massager",
    category: "Foot Massagers",
    categorySlug: "foot-massagers",
    primaryKeyword: "foot and calf massager manufacturer",
    secondaryKeywords: ["leg and foot massager supplier", "premium foot massager OEM", "calf massage machine factory"],
    intent: "transactional",
    metaTitle: "Foot & Calf Massager Manufacturer | Premium OEM Supplier",
    metaDescription:
      "Foot and calf massager manufacturer producing enclosed platforms covering feet and lower calves for premium wellness and private-label programs.",
    summary: "A larger enclosed massage platform covering feet and lower calves for premium wellness programs.",
    images: gallery(10, 6),
    tags: ["Foot and lower-calf format", "Private label", "Sample inquiry"],
    specs: {
      model: "HT-FN001",
      colors: "Grey, Dark Grey",
      power: "Input 100-240V 50/60Hz, 12V 2A; Power 24W",
      packageSize: "33 x 16 x 17.5 cm",
      cartonSize: "51 x 35 x 38.5 cm (6 pcs/carton)",
    },
    features: [
      "Six modes: auto, massage, kneading, relax, calf-focused and foot-focused",
      "Covers feet, heels and calves in one unit",
      "Three intensity levels: weak, medium and strong",
      "Two heat levels plus off, applied at the feet",
      "Three-button control for programme, heating and intensity",
      "10-minute auto-off timer",
    ],
    customization: ["Housing finish", "Controls", "Voltage", "Gift box"],
    applications: ["Premium wellness retail", "Clinic and spa supply", "High-value gifting"],
  },
  {
    slug: "air-compression-leg-massager",
    name: "Air Compression Leg Massager",
    category: "Leg Massagers",
    categorySlug: "leg-massagers",
    primaryKeyword: "air compression leg massager manufacturer",
    secondaryKeywords: ["calf compression massager supplier", "pneumatic leg massager OEM", "circulation leg massager factory"],
    intent: "transactional",
    metaTitle: "Air Compression Leg Massager Manufacturer | OEM Supplier",
    metaDescription:
      "Air compression leg massager manufacturer supplying calf-wrap pneumatic platforms for recovery, wellness retail and private-label programs.",
    summary: "A calf-wrap compression format for recovery, wellness and private-label retail programs.",
    images: gallery(6, 6),
    tags: ["Calf wrap", "OEM / ODM", "Compression format"],
    specs: {
      model: "FM10-3",
      colors: "Pink / Grey",
      battery: "2000 mAh; 3.7V operating, 2A charging",
      power: "5W",
      productSize: "57 x 30 cm",
      netGrossWeight: "490 g",
      packageSize: "Single-leg box 32 x 17 x 7 cm; double-leg box 32 x 19.5 x 8.6 cm",
      cartonSize: "Single leg 47.5 x 34 x 53 cm (21 pcs); pair 56 x 34 x 56 cm (18 pcs)",
    },
    features: [
      "Progressive air-pressure massage with a 360-degree wrap",
      "Pressure applied from the bottom upward for lower-leg relief first",
      "Three heat settings: 40 C daily care, 45 C post-workout, 50 C joint comfort",
      "Up to nine combination modes across heat and massage",
      "Three modes (leg relief, kneading, lifting) with three intensity levels",
      "Digital touchscreen for one-handed control",
      "Wide adjustable Velcro straps to fit the whole family",
      "Stain-resistant linen outer fabric, soft and breathable",
      "2000 mAh battery for cordless use",
    ],
    customization: ["Sleeve material", "Controller", "Logo", "Packaging"],
    applications: ["Recovery and wellness retail", "Senior mobility channels", "Online health brands"],
  },
  {
    slug: "compression-leg-massager-boots",
    name: "Compression Leg Massager Boots",
    category: "Leg Massagers",
    categorySlug: "leg-massagers",
    primaryKeyword: "compression leg massager boots manufacturer",
    secondaryKeywords: ["recovery boots supplier China", "athlete compression boots OEM", "full leg massager factory"],
    intent: "transactional",
    metaTitle: "Compression Boots Manufacturer | Leg Recovery OEM Supplier",
    metaDescription:
      "Compression leg massager boots manufacturer producing full lower-leg recovery systems with foot coverage for sports recovery and wellness brands.",
    summary: "Full lower-leg compression boots with foot coverage for recovery and wellness programs.",
    images: gallery(8, 5),
    tags: ["Leg and foot coverage", "Controller included", "OEM / ODM"],
    features: ["Boot-style air chambers", "Lower-leg and foot coverage", "Multiple compression programmes"],
    customization: ["Sleeve size", "Controller", "Color", "Carrying bag"],
    applications: ["Sports recovery brands", "Training facilities", "Physiotherapy distribution"],
  },
  {
    slug: "shiatsu-massage-pillow",
    name: "Shiatsu Massage Pillow",
    category: "Massage Pillows & Cushions",
    categorySlug: "massage-pillows-cushions",
    primaryKeyword: "shiatsu massage pillow manufacturer",
    secondaryKeywords: ["kneading massage pillow supplier", "neck and back massage pillow OEM", "wholesale massage pillow China"],
    intent: "transactional",
    metaTitle: "Shiatsu Massage Pillow Manufacturer | OEM & Wholesale",
    metaDescription:
      "Shiatsu massage pillow manufacturer supplying compact kneading pillows for neck, back and waist positioning in retail and private-label ranges.",
    summary: "A compact kneading massage pillow for neck, back and waist positioning.",
    images: gallery(16, 6),
    tags: ["Compact pillow", "Kneading nodes", "OEM / ODM"],
    specs: {
      model: "WY-P001",
      colors: "Black/White, Red, Brown, Black, Blue, Beige Check",
      power: "Input 110-240V; Output DC 12V 2A; Rated power 24W",
      productSize: "36 x 18 x 11.5 cm",
      netGrossWeight: "1.1 kg / 1.5 kg",
      packageSize: "36 x 13.5 x 18.5 cm",
      cartonSize: "70.5 x 37 x 39 cm (10 pcs/carton)",
    },
    features: [
      "Four soft shiatsu heads that reverse in two directions",
      "Kneading massage combined with infrared heating",
      "15-minute auto-off timer",
      "Covers neck, back, waist, abdomen, arm, leg and foot",
      "Six colourways available for range segmentation",
      "Mains adapter and car plug supplied for home, office or vehicle use",
    ],
    customization: ["Fabric", "Color", "Logo", "Power configuration"],
    applications: ["Home and office retail", "Automotive channels", "Gift programs"],
  },
  {
    slug: "heated-massage-pillow",
    name: "Heated Massage Pillow",
    category: "Massage Pillows & Cushions",
    categorySlug: "massage-pillows-cushions",
    primaryKeyword: "heated massage pillow supplier",
    secondaryKeywords: ["massage pillow with heat manufacturer", "car massage pillow OEM", "soft massage cushion wholesale"],
    intent: "transactional",
    metaTitle: "Heated Massage Pillow Supplier | OEM Factory China",
    metaDescription:
      "Heated massage pillow supplier producing soft compact platforms with heat options for home, office and vehicle wellness product ranges.",
    summary: "A soft compact massage pillow platform for home, office and vehicle wellness ranges.",
    images: gallery(17, 5),
    tags: ["Compact design", "Heat option", "Private label"],
    features: ["Soft pillow construction", "Visible kneading area", "Optional heat function"],
    customization: ["Upholstery", "Color", "Controls", "Packaging"],
    applications: ["Home comfort retail", "Vehicle accessory channels", "Seasonal gifting"],
  },
  {
    slug: "full-back-massage-seat-cushion",
    name: "Full Back Massage Seat Cushion",
    category: "Massage Pillows & Cushions",
    categorySlug: "massage-pillows-cushions",
    primaryKeyword: "full back massage seat cushion manufacturer",
    secondaryKeywords: ["massage chair pad supplier", "back massage cushion OEM", "office chair massager factory"],
    intent: "transactional",
    metaTitle: "Massage Seat Cushion Manufacturer | Full Back Pad OEM Supplier",
    metaDescription:
      "Full back massage seat cushion manufacturer supplying chair-mounted massage pads with seat, back and neck sections for office, home and automotive channels.",
    summary: "A chair-mounted full-back massage pad with seat, back and neck support sections.",
    images: gallery(19, 6, [5, 6]),
    tags: ["Full-back format", "Chair-mounted", "B2B supply"],
    specs: {
      model: "WY-MC013",
      colors: "Black, Grey",
      power: "Rated 24V 30W; Input 110-240V; Output DC 12.6V 1A",
      productSize: "78.5 x 23.5 x 44.5 cm",
      netGrossWeight: "5.4 kg / 6.8 kg",
      packageSize: "76 x 20 x 44 cm",
    },
    features: [
      "Four techniques in one unit: kneading, pressing, rolling and pinching",
      "35-60 mm adjustable head spacing with 30 mm variable depth",
      "Widened upper heads for the shoulder and neck muscle group",
      "Extended lower swing arms reaching the trapezius",
      "Adjustable neck height to suit different body heights",
      "Heat function applied during massage",
      "High-frequency vibration section for the hip area",
      "Three speeds: gentle, soothing and vigorous",
      "15-minute auto-off timer",
      "Breathable skin-friendly mesh fabric with remote-control storage pocket",
    ],
    customization: ["Upholstery", "Massage zones", "Controller", "Packaging"],
    applications: ["Office furniture channels", "Automotive accessories", "Home wellness retail"],
  },
  {
    slug: "heated-hand-massager",
    name: "Heated Hand Massager",
    category: "Targeted Body Massagers",
    categorySlug: "targeted-body-massagers",
    primaryKeyword: "heated hand massager manufacturer",
    secondaryKeywords: ["electric hand massager supplier", "palm massager OEM factory", "hand therapy device wholesale"],
    intent: "transactional",
    metaTitle: "Heated Hand Massager Manufacturer | OEM & Private Label",
    metaDescription:
      "Heated hand massager manufacturer producing enclosed hand massage devices with heat functions for wellness, senior care and private-label ranges.",
    summary: "An enclosed hand massage device with heat function for wellness and personal-care ranges.",
    images: gallery(21, 5),
    tags: ["Enclosed hand chamber", "Heat Function", "Private label"],
    specs: {
      model: "WY-ST-1803",
      colors: "White",
      battery: "2000 mAh; 120 min charge, 90 min runtime",
      power: "Input 5V DC 1A; charging power 5W",
      netGrossWeight: "1320 g gross with colour box",
      packageSize: "28.8 x 18.6 x 14 cm",
      cartonSize: "44.5 x 39.5 x 59.5 cm (12 pcs/carton)",
      cartonWeight: "17 kg",
    },
    features: [
      "Four massage modes including a finger-stretching technique",
      "Three constant-temperature heat settings with 3-second rapid heating",
      "Five intensity levels for precise adjustment",
      "Built-in silicone nubs for point-to-point deep pressure",
      "2000 mAh battery: 120-minute charge for 90 minutes of use",
    ],
    customization: ["Shell color", "Controls", "Logo", "Gift box"],
    applications: ["Senior care retail", "Wellness e-commerce", "Health gifting"],
  },
  {
    slug: "kneading-hand-massager",
    name: "Kneading Hand Massager",
    category: "Targeted Body Massagers",
    categorySlug: "targeted-body-massagers",
    primaryKeyword: "kneading hand massager supplier",
    secondaryKeywords: ["hand massage machine manufacturer", "finger massager OEM China", "wholesale hand massager device"],
    intent: "transactional",
    metaTitle: "Kneading Hand Massager Supplier | OEM Manufacturer China",
    metaDescription:
      "Kneading hand massager supplier producing enclosed devices with finger-style kneading modules for wellness retail and private-label programs.",
    summary: "An enclosed hand massage device with finger-like kneading modules.",
    images: gallery(22, 4),
    tags: ["Kneading format", "Four Massage Modes", "OEM / ODM"],
    features: ["Enclosed hand chamber", "Finger-like kneading modules", "Four selectable massage modes"],
    customization: ["Shell finish", "Mode control", "Logo", "Packaging"],
    applications: ["Wellness retail", "Office and desk-worker channels", "Health distribution"],
  },
  {
    slug: "heated-lumbar-massager-belt",
    name: "Heated Lumbar Massager Belt",
    category: "Targeted Body Massagers",
    categorySlug: "targeted-body-massagers",
    primaryKeyword: "heated lumbar massager belt manufacturer",
    secondaryKeywords: ["waist massager supplier China", "back massage belt OEM", "lumbar heat belt factory"],
    intent: "transactional",
    metaTitle: "Lumbar Massage Belt Manufacturer | Heated Waist Massager OEM",
    metaDescription:
      "Heated lumbar massager belt manufacturer supplying wearable lower-back massage belts with heat and vibration for wellness and private-label programs.",
    summary: "A wearable lower-back massage belt with heat and vibration functions.",
    images: gallery(20, 4),
    tags: ["Lumbar support", "Heat Function", "Vibration Massage"],
    specs: {
      model: "WY-HZ-Y5",
      colors: "Khaki",
      battery: "2600 mAh, Type-C charging",
      power: "Input 5V; power 4W",
      netGrossWeight: "660 g / 1.5 kg",
      packageSize: "27 x 27 x 11 cm",
    },
    features: [
      "Four adjustable support belts to fit different body sizes",
      "Double C-type bionic support design for lumbar stability",
      "Two bionic vertebrae supports plus four PP support strips",
      "360-degree enveloping design with high-density support plate",
      "Carbon-fibre heating across approximately 8000 mm2",
      "Five-second rapid heating with five-level temperature control",
      "Five vibration levels: soft (1-2), common (3-4) and strong (5)",
      "Two massage modes with a 15-minute auto-off timer",
      "2600 mAh Type-C battery for cordless wear",
    ],
    customization: ["Fabric", "Controller", "Logo", "Retail packaging"],
    applications: ["Back-care retail", "Occupational wellness", "Online health brands"],
  },
  {
    slug: "heated-ankle-massager",
    name: "Heated Ankle Massager",
    category: "Targeted Body Massagers",
    categorySlug: "targeted-body-massagers",
    primaryKeyword: "heated ankle massager supplier",
    secondaryKeywords: ["ankle massage wrap manufacturer", "joint massager OEM factory", "ankle heat therapy wholesale"],
    intent: "transactional",
    metaTitle: "Heated Ankle Massager Supplier | Joint Wrap OEM Manufacturer",
    metaDescription:
      "Heated ankle massager supplier producing compact ankle wraps with heat and vibration for targeted recovery and private-label wellness ranges.",
    summary: "A compact wrap designed around the ankle for targeted heat and vibration product lines.",
    images: gallery(7, 6, [1, 2, 3, 4, 5, 6]),
    tags: ["Ankle wrap", "Heat Function", "Targeted format"],
    specs: {
      model: "WY-FN071",
      battery: "2000 mAh, Type-C charging",
      power: "5V",
      netGrossWeight: "250 g",
      packageSize: "13 x 5.5 x 17.9 cm",
      cartonSize: "30 pcs/carton",
    },
    features: [
      "Dual-motor vibration with three modes: wave, continuous and rhythmic",
      "Five-level hot compress adjustable from 40 C to 60 C",
      "NTC temperature-control chip holds a constant compress temperature",
      "Carbon-fibre heating element emitting far-infrared radiation",
      "360-degree ankle wrap with non-slip fabric",
      "Large LCD display with push-button control",
      "15-minute auto-off timer",
      "2000 mAh Type-C battery for cordless portable use",
    ],
    customization: ["Fabric", "Temperature control", "Logo", "Retail package"],
    applications: ["Sports recovery", "Senior mobility", "Pharmacy channels"],
  },
  {
    slug: "ems-facial-massager",
    name: "EMS Facial Massager",
    category: "Targeted Body Massagers",
    categorySlug: "targeted-body-massagers",
    primaryKeyword: "EMS facial massager manufacturer",
    secondaryKeywords: ["facial massage device supplier", "beauty device OEM China", "face massager private label"],
    intent: "transactional",
    metaTitle: "EMS Facial Massager Manufacturer | Beauty Device OEM Supplier",
    metaDescription:
      "EMS facial massager manufacturer supplying handheld facial-care devices with EMS, vibration and heat functions for beauty and private-label brands.",
    summary: "A handheld facial-care device with EMS, vibration and heat functions.",
    images: gallery(15, 6, [1, 5, 6]),
    tags: ["EMS Microcurrent", "Heat Function", "Beauty device"],
    specs: {
      model: "DYM-062",
      colors: "White, Black",
      battery: "2000 mAh",
      power: "USB Type-C 5V/1A; charging voltage 100-240V",
      productSize: "150 x 110 x 30 mm",
      netGrossWeight: "340 g / 480 g",
      packageSize: "180 x 180 x 40 mm",
      cartonSize: "39.2 x 37.5 x 37.5 cm (40 pcs/carton)",
      cartonWeight: "20 kg",
    },
    features: [
      "Triple action in one tool: EMS microcurrent, vibration and heat",
      "Nine-level heat from 36 C to 60 C",
      "Nine-level high-frequency vibration",
      "Nine-level EMS microcurrent with maximum output below 100V",
      "Three independent modes (heat, microcurrent, vibration), nine levels each",
      "Stepless speed control so users can build up from the lowest level",
      "2000 mAh battery with 10-minute auto shut-off when idle",
      "Holds domestic and EU design patents; CE certified (No. 00460AX0533CE)",
    ],
    customization: ["Color", "Logo", "Controls", "Retail packaging"],
    applications: ["Beauty retail", "Skincare brands", "Beauty e-commerce"],
  },
];

export function getProduct(slug: string) {
  return products.find((product) => product.slug === slug);
}
