export type Product = {
  slug: string;
  name: string;
  category: string;
  primaryKeyword: string;
  sourceTerm: string;
  summary: string;
  images: string[];
  tags: string[];
  features: string[];
  customization: string[];
  complianceNote?: string;
};

export const categories = [
  { slug: "neck-shoulder-massagers", name: "Neck & Shoulder Massagers", note: "Wearable, wrap and kneading formats" },
  { slug: "leg-foot-massagers", name: "Leg & Foot Massagers", note: "Compression, heat and enclosed systems" },
  { slug: "massage-guns", name: "Massage Guns", note: "Percussion and hot-and-cold recovery concepts" },
  { slug: "massage-pillows-mats", name: "Massage Pillows & Mats", note: "Compact pillows and full-back seat pads" },
  { slug: "targeted-massagers", name: "Targeted Massagers", note: "Hand, waist, ankle and facial formats" },
];

const gallery = (folder: number, count: number, pngPositions: number[] = []) =>
  Array.from({ length: count }, (_, index) => `/products/${folder}/image-${index + 1}.${pngPositions.includes(index + 1) ? "png" : "jpg"}`);

export const products: Product[] = [
  {
    slug: "wearable-neck-massager",
    name: "Wearable Neck Massager",
    category: "Neck & Shoulder Massagers",
    primaryKeyword: "wearable neck massager manufacturer",
    sourceTerm: "Neck & Shoulder Massager",
    summary: "An open-neck wearable format for private-label wellness and personal-care programs.",
    images: gallery(1, 4), tags: ["OEM / ODM", "Private label", "Sample inquiry"],
    features: ["Open-neck wearable form", "Compact retail concept", "Functions confirmed per quotation"],
    customization: ["Logo", "Color", "Packaging", "Market configuration"],
  },
  {
    slug: "shiatsu-neck-shoulder-massager",
    name: "Shiatsu Neck and Shoulder Massager",
    category: "Neck & Shoulder Massagers",
    primaryKeyword: "shiatsu neck and shoulder massager manufacturer",
    sourceTerm: "Neck & Shoulder Massager",
    summary: "A plug-in wrap-style massage platform supplied with home and vehicle power options.",
    images: gallery(2, 5, [1, 3, 4, 5]), tags: ["Home and car use", "OEM / ODM", "B2B supply"],
    features: ["Wrap-style construction", "Home and vehicle power options shown", "Massage functions confirmed per model"],
    customization: ["Upholstery", "Control layout", "Logo", "Retail box"],
  },
  {
    slug: "kneading-neck-shoulder-massager",
    name: "Kneading Neck and Shoulder Massager",
    category: "Neck & Shoulder Massagers",
    primaryKeyword: "kneading neck and shoulder massager supplier",
    sourceTerm: "Neck & Shoulder Massager",
    summary: "A pull-strap shoulder wrap designed for wholesale and private-label massage ranges.",
    images: gallery(3, 6), tags: ["Pull-strap design", "Private label", "Wholesale"],
    features: ["Neck and shoulder wrap", "Manual pull-strap positioning", "Model-specific functions on request"],
    customization: ["Fabric", "Color", "Controls", "Packaging"],
  },
  {
    slug: "heated-neck-shoulder-massager",
    name: "Heated Neck and Shoulder Massager",
    category: "Neck & Shoulder Massagers",
    primaryKeyword: "heated neck and shoulder massager manufacturer",
    sourceTerm: "Neck & Shoulder Massager",
    summary: "A U-shaped shoulder massage platform with an integrated control area for branded programs.",
    images: gallery(4, 6), tags: ["Heat option", "OEM / ODM", "Retail-ready format"],
    features: ["U-shaped shoulder wrap", "Integrated controls", "Heating configuration confirmed per model"],
    customization: ["Logo", "Materials", "Heat settings", "Gift box"],
  },
  {
    slug: "wraparound-shoulder-massager",
    name: "Wraparound Shoulder Massager",
    category: "Neck & Shoulder Massagers",
    primaryKeyword: "wraparound shoulder massager supplier",
    sourceTerm: "Neck & Shoulder Massager",
    summary: "A padded wraparound massage format for shoulder and upper-body product collections.",
    images: gallery(5, 4), tags: ["Padded wrap", "OEM available", "B2B quotation"],
    features: ["Wide padded construction", "Shoulder-wrap product form", "Exact body-use claims confirmed per model"],
    customization: ["Surface material", "Color", "Control panel", "Branding"],
  },
  {
    slug: "air-compression-leg-massager",
    name: "Air Compression Leg Massager",
    category: "Leg & Foot Massagers",
    primaryKeyword: "air compression leg massager manufacturer",
    sourceTerm: "Leg Massager",
    summary: "A calf-wrap compression format for recovery, wellness and private-label retail programs.",
    images: gallery(6, 6), tags: ["Calf wrap", "OEM / ODM", "Compression format"],
    features: ["Wearable calf sleeves", "External control panel shown", "Pressure modes confirmed per model"],
    customization: ["Sleeve material", "Controller", "Logo", "Packaging"],
  },
  {
    slug: "heated-ankle-massager",
    name: "Heated Ankle Massager",
    category: "Targeted Massagers",
    primaryKeyword: "heated ankle massager supplier",
    sourceTerm: "Other Massagers",
    summary: "A compact wrap designed around the ankle for targeted heat and vibration product lines.",
    images: gallery(7, 6, [1, 2, 3, 4, 5, 6]), tags: ["Ankle wrap", "Heat shown", "Targeted format"],
    features: ["Ankle-focused wearable form", "Heat levels shown in source imagery", "Vibration configuration shown"],
    customization: ["Fabric", "Temperature control", "Logo", "Retail package"],
  },
  {
    slug: "compression-leg-massager-boots",
    name: "Compression Leg Massager Boots",
    category: "Leg & Foot Massagers",
    primaryKeyword: "compression leg massager boots manufacturer",
    sourceTerm: "Leg Massager",
    summary: "Full lower-leg compression boots with foot coverage for recovery and wellness programs.",
    images: gallery(8, 5), tags: ["Leg and foot coverage", "Controller included", "OEM / ODM"],
    features: ["Boot-style air chambers", "Lower-leg and foot coverage", "Program details confirmed per quotation"],
    customization: ["Sleeve size", "Controller", "Color", "Carrying bag"],
  },
  {
    slug: "shiatsu-foot-massager-machine",
    name: "Shiatsu Foot Massager Machine",
    category: "Leg & Foot Massagers",
    primaryKeyword: "shiatsu foot massager manufacturer",
    sourceTerm: "Foot Massager",
    summary: "An enclosed dual-foot massage platform for branded home-wellness ranges.",
    images: gallery(9, 4, [1, 2, 3, 4]), tags: ["Enclosed foot system", "OEM / ODM", "Wholesale"],
    features: ["Dual-foot enclosure", "Massage and heat functions shown", "Configuration confirmed per model"],
    customization: ["Housing color", "Control panel", "Power configuration", "Packaging"],
  },
  {
    slug: "foot-and-calf-massager",
    name: "Foot and Calf Massager",
    category: "Leg & Foot Massagers",
    primaryKeyword: "foot and calf massager manufacturer",
    sourceTerm: "Foot Massager",
    summary: "A larger enclosed massage platform covering feet and lower calves for premium wellness programs.",
    images: gallery(10, 6), tags: ["Foot and lower-calf format", "Private label", "Sample inquiry"],
    features: ["Deep foot wells", "Lower-calf contact area", "Model-specific programs available"],
    customization: ["Housing finish", "Controls", "Voltage", "Gift box"],
  },
  {
    slug: "hot-cold-massage-gun",
    name: "Hot and Cold Massage Gun",
    category: "Massage Guns",
    primaryKeyword: "hot and cold massage gun manufacturer",
    sourceTerm: "Massage Gun / Fascia Gun",
    summary: "A percussion massage gun concept with a hot-and-cold attachment shown for recovery ranges.",
    images: gallery(11, 6), tags: ["Hot and cold head", "Percussion format", "OEM / ODM"],
    features: ["Interchangeable heads", "Hot and cold therapy head shown", "Temperature performance confirmed by specification"],
    customization: ["Color", "Attachments", "Logo", "Carrying case"],
  },
  {
    slug: "deep-tissue-massage-gun",
    name: "Deep Tissue Massage Gun",
    category: "Massage Guns",
    primaryKeyword: "deep tissue massage gun manufacturer",
    sourceTerm: "Massage Gun / Fascia Gun",
    summary: "A full-size percussion massage gun with multiple attachment options for wholesale programs.",
    images: gallery(12, 6), tags: ["Multiple attachments", "OEM available", "Wholesale"],
    features: ["Full-size percussion form", "Multiple heads shown", "Speed and battery data confirmed per model"],
    customization: ["Shell color", "Attachments", "Display", "Case and packaging"],
  },
  {
    slug: "mini-massage-gun",
    name: "Mini Massage Gun",
    category: "Massage Guns",
    primaryKeyword: "mini massage gun manufacturer",
    sourceTerm: "Massage Gun / Fascia Gun",
    summary: "A compact percussion massage gun platform for travel, gifting and e-commerce ranges.",
    images: gallery(13, 6), tags: ["Compact format", "Private label", "Retail program"],
    features: ["Compact T-shaped body", "Interchangeable heads shown", "Portable product positioning"],
    customization: ["Color", "Logo", "Attachment set", "Gift box"],
  },
  {
    slug: "cooling-massage-gun",
    name: "Cooling Massage Gun",
    category: "Massage Guns",
    primaryKeyword: "cooling massage gun supplier",
    sourceTerm: "Massage Gun / Fascia Gun",
    summary: "A full-size percussion massage gun concept with a rear cooling design shown in source imagery.",
    images: gallery(14, 6), tags: ["Cooling design shown", "OEM / ODM", "Accessory set"],
    features: ["Full-size percussion format", "Rear cooling element shown", "Display and speed details confirmed per model"],
    customization: ["Color", "Logo", "Head set", "Storage case"],
  },
  {
    slug: "ems-facial-massager",
    name: "EMS Facial Massager",
    category: "Targeted Massagers",
    primaryKeyword: "EMS facial massager manufacturer",
    sourceTerm: "Face Massager / Facial Massager",
    summary: "A handheld facial-care format with EMS, vibration and heat functions shown in product imagery.",
    images: gallery(15, 6, [1, 5, 6]), tags: ["EMS shown", "Heat shown", "Beauty device"],
    features: ["Handheld facial format", "EMS and vibration claims shown", "Performance substantiation confirmed before order"],
    customization: ["Color", "Logo", "Controls", "Retail packaging"],
  },
  {
    slug: "shiatsu-massage-pillow",
    name: "Shiatsu Massage Pillow",
    category: "Massage Pillows & Mats",
    primaryKeyword: "shiatsu massage pillow manufacturer",
    sourceTerm: "Massage Pillow",
    summary: "A compact kneading massage pillow for neck, back and waist positioning.",
    images: gallery(16, 6), tags: ["Compact pillow", "Kneading nodes", "OEM / ODM"],
    features: ["Butterfly pillow form", "Visible kneading nodes", "Multi-position product concept"],
    customization: ["Fabric", "Color", "Logo", "Power configuration"],
  },
  {
    slug: "heated-massage-pillow",
    name: "Heated Massage Pillow",
    category: "Massage Pillows & Mats",
    primaryKeyword: "heated massage pillow supplier",
    sourceTerm: "Massage Pillow",
    summary: "A soft compact massage pillow platform for home, office and vehicle wellness ranges.",
    images: gallery(17, 5), tags: ["Compact design", "Heat option", "Private label"],
    features: ["Soft pillow construction", "Visible kneading area", "Heating option confirmed per model"],
    customization: ["Upholstery", "Color", "Controls", "Packaging"],
  },
  {
    slug: "u-shaped-neck-massager",
    name: "U-Shaped Neck Massager",
    category: "Neck & Shoulder Massagers",
    primaryKeyword: "U shaped neck massager manufacturer",
    sourceTerm: "Neck & Shoulder Massager",
    summary: "A structured U-shaped neck massage platform for consumer wellness and gifting ranges.",
    images: gallery(18, 6), tags: ["U-shaped form", "Neck-focused", "OEM available"],
    features: ["Structured neck fit", "Massage nodes shown", "Heat and controls confirmed per specification"],
    customization: ["Surface material", "Color", "Logo", "Gift box"],
  },
  {
    slug: "full-back-massage-seat-cushion",
    name: "Full Back Massage Seat Cushion",
    category: "Massage Pillows & Mats",
    primaryKeyword: "full back massage seat cushion manufacturer",
    sourceTerm: "Massage Mat",
    summary: "A chair-mounted full-back massage pad with seat, back and neck support sections.",
    images: gallery(19, 6, [5, 6]), tags: ["Full-back format", "Chair-mounted", "B2B supply"],
    features: ["Seat and back pad", "Neck support area", "Wired control shown"],
    customization: ["Upholstery", "Massage zones", "Controller", "Packaging"],
  },
  {
    slug: "heated-lumbar-massager-belt",
    name: "Heated Lumbar Massager Belt",
    category: "Targeted Massagers",
    primaryKeyword: "heated lumbar massager belt manufacturer",
    sourceTerm: "Waist Massager / Lumbar Massager",
    summary: "A wearable lower-back massage belt with heat and vibration functions shown.",
    images: gallery(20, 4), tags: ["Lumbar support", "Heat shown", "Vibration shown"],
    features: ["Wide waist wrap", "Lower-back positioning", "Heat and vibration functions shown"],
    customization: ["Fabric", "Controller", "Logo", "Retail packaging"],
  },
  {
    slug: "heated-hand-massager",
    name: "Heated Hand Massager",
    category: "Targeted Massagers",
    primaryKeyword: "heated hand massager manufacturer",
    sourceTerm: "Hand Massager",
    summary: "An enclosed hand massage format with heat shown for wellness and personal-care ranges.",
    images: gallery(21, 5), tags: ["Enclosed hand chamber", "Heat shown", "Private label"],
    features: ["Hand and wrist entry", "Heat function shown", "Massage mechanism confirmed per model"],
    customization: ["Shell color", "Controls", "Logo", "Gift box"],
  },
  {
    slug: "kneading-hand-massager",
    name: "Kneading Hand Massager",
    category: "Targeted Massagers",
    primaryKeyword: "kneading hand massager supplier",
    sourceTerm: "Hand Massager",
    summary: "An enclosed hand massage device with finger-like kneading modules shown in source imagery.",
    images: gallery(22, 4), tags: ["Kneading format", "Four modes shown", "OEM / ODM"],
    features: ["Enclosed hand chamber", "Finger-like kneading modules shown", "Four modes shown in product imagery"],
    customization: ["Shell finish", "Mode control", "Logo", "Packaging"],
  },
];

export function getProduct(slug: string) {
  return products.find((product) => product.slug === slug);
}
